"""Emitter base: shared helpers for rendering IR steps to target code."""

from __future__ import annotations

from ..ir import Program, Step


def header_comment(prog: Program, target: str, source_path: str = "") -> str:
    lines = [
        f"# Generated by sas2databricks -> target: {target}",
        f"# Source: {source_path or '(in-memory)'}",
        "# Review every step flagged 'MANUAL REVIEW' / low confidence before running.",
    ]
    return "\n".join(lines)


def step_banner(step: Step) -> str:
    p = step.prov
    flag = " [REVIEW]" if p.needs_review() else ""
    notes = ("\n# notes: " + "; ".join(p.notes)) if p.notes else ""
    return (
        f"# -- step: {step.name} (kind={step.kind}, engine={p.engine.value}, "
        f"conf={p.confidence:.2f}{flag}) -- SAS lines {p.start_line}-{p.end_line}{notes}"
    )


def safe_name(name: str) -> str:
    """Turn a SAS dataset name (lib.table) into a valid identifier."""
    return name.replace(".", "_").replace("-", "_")
