"""Emit a Databricks Asset Bundle (``databricks.yml``).

Two flavours are produced:

* :func:`emit` — a standalone bundle for **one** migrated program. Each IR step becomes a
  notebook task (reusing the ``workflow`` target's task graph), so the step dependencies are
  preserved. The notebooks themselves are expected at ``notebook_base`` in the workspace.
* :func:`project_bundle` — a deployable bundle for a **whole project**: one task per migrated
  ``.sas`` file, pointing at the notebooks written alongside ``databricks.yml`` under ``src/``.
  This is what ``s2db migrate --bundle`` assembles.

Both declare ``dev`` and ``prod`` deployment targets so the result ships with
``databricks bundle deploy``.
"""

from __future__ import annotations

import yaml

from ..ir import Program
from .base import safe_name
from .workflow_emitter import build_tasks

_HEADER = (
    "# Databricks Asset Bundle generated by sas2databricks.\n"
    "# Deploy with:  databricks bundle deploy -t dev\n"
    "# Run with:     databricks bundle run <job_key> -t dev\n"
)


def build_bundle(*, bundle_name: str, job_name: str, tasks: list[dict]) -> dict:
    """Assemble the Databricks Asset Bundle definition as a plain dict (deterministic order)."""
    job_key = f"{bundle_name}_job"
    return {
        "bundle": {"name": bundle_name},
        "resources": {
            "jobs": {
                job_key: {
                    "name": job_name,
                    "tags": {"generated_by": "sas2databricks"},
                    "tasks": tasks,
                }
            }
        },
        "targets": {
            "dev": {"mode": "development", "default": True},
            "prod": {"mode": "production"},
        },
    }


def render_bundle(definition: dict) -> str:
    """Serialise a bundle definition dict to YAML with the standard header."""
    body = yaml.safe_dump(definition, sort_keys=False, width=100)
    return _HEADER + body


def emit(
    prog: Program,
    *,
    source_path: str = "",
    bundle_name: str | None = None,
    notebook_base: str = "${workspace.file_path}/src",
) -> str:
    """Single-program bundle: one notebook task per IR step, wired by step dependencies."""
    name = safe_name(bundle_name or _stem(source_path) or "sas_migration")
    definition = build_bundle(
        bundle_name=name,
        job_name=f"{name} (SAS migration)",
        tasks=build_tasks(prog, notebook_base=notebook_base),
    )
    return render_bundle(definition)


def project_bundle(
    bundle_name: str,
    stems: list[str],
    *,
    src_dir: str = "src",
    job_name: str | None = None,
) -> str:
    """Project bundle: one notebook task per migrated file under ``src_dir``.

    ``stems`` are the file stems whose notebooks live at ``<src_dir>/<stem>``; the Databricks
    CLI uploads those local notebooks on ``bundle deploy``.
    """
    name = safe_name(bundle_name or "sas_migration")
    seen: set[str] = set()
    tasks: list[dict] = []
    for stem in stems:
        key = safe_name(stem)
        while key in seen:  # guard against stem collisions after sanitising
            key += "_"
        seen.add(key)
        tasks.append(
            {
                "task_key": key,
                "notebook_task": {"notebook_path": f"{src_dir}/{stem}"},
            }
        )
    definition = build_bundle(
        bundle_name=name,
        job_name=job_name or f"{name} (SAS project migration)",
        tasks=tasks,
    )
    return render_bundle(definition)


def _stem(source_path: str) -> str:
    if not source_path:
        return ""
    base = source_path.replace("\\", "/").rsplit("/", 1)[-1]
    return base.rsplit(".", 1)[0]
