"""Emit a Delta Live Tables (DLT) pipeline from the IR.

Each IR step becomes an ``@dlt.table`` whose body returns a DataFrame. Upstream datasets
are referenced via ``dlt.read`` / ``dlt.read_stream`` so DLT wires the dependency graph.
"""

from __future__ import annotations

from ..ir import AggStep, DataStep, Program, SqlStep, Step
from . import sparksql_emitter
from .base import safe_name


def emit(prog: Program, *, source_path: str = "") -> str:
    out = [
        "# Databricks notebook source",
        "# Generated by sas2databricks -> target: Delta Live Tables",
        f"# Source: {source_path or '(in-memory)'}",
        "import dlt",
        "from pyspark.sql import functions as F",
        "",
    ]
    for step in prog.steps:
        out.append(_table(step))
        out.append("")
    return "\n".join(out)


def _table(step: Step) -> str:
    name = safe_name(step.name)
    flag = "  # [REVIEW]" if step.prov.needs_review() else ""
    if isinstance(step, SqlStep):
        body = f'    return spark.sql("""{step.sql}""")'
    elif isinstance(step, (AggStep, DataStep)):
        sql = sparksql_emitter._emit_step(step)
        # strip the CREATE VIEW wrapper, keep the SELECT
        select = sql.split(" AS\n", 1)[-1].rstrip(";")
        body = f'    return spark.sql("""{select}""")'
    else:
        body = "    # MANUAL REVIEW: implement this DLT table body\n    return spark.range(0)"

    comment = f"SAS {step.kind}"
    return (
        f"@dlt.table(name={name!r}, comment={comment!r}){flag}\n"
        f"def {name}():\n{body}"
    )
