"""Emit Spark SQL / Databricks SQL from the IR."""

from __future__ import annotations

from ..ir import AggStep, DataStep, Program, ReportStep, SqlStep, Step
from .base import safe_name

_AGG_SQL = {
    "avg": "avg({c})",
    "sum": "sum({c})",
    "count": "count({c})",
    "min": "min({c})",
    "max": "max({c})",
    "stddev": "stddev({c})",
    "variance": "variance({c})",
    "percentile_approx_25": "percentile_approx({c}, 0.25)",
    "percentile_approx_50": "percentile_approx({c}, 0.50)",
    "percentile_approx_75": "percentile_approx({c}, 0.75)",
}


def emit(prog: Program, *, source_path: str = "") -> str:
    out = [
        "-- Generated by sas2databricks -> target: spark sql",
        f"-- Source: {source_path or '(in-memory)'}",
    ]
    for step in prog.steps:
        sql = _emit_step(step)
        if sql:
            out.append(f"\n-- step: {step.name} (conf={step.prov.confidence:.2f})\n{sql}")
    return "\n".join(out) + "\n"


def _emit_step(step: Step) -> str:
    if isinstance(step, SqlStep):
        view = safe_name(step.name)
        return f"CREATE OR REPLACE TEMP VIEW {view} AS\n{step.sql};"
    if isinstance(step, AggStep):
        return _agg(step)
    if isinstance(step, DataStep):
        return _data(step)
    if isinstance(step, ReportStep):
        cols = ", ".join(step.columns) if step.columns else "*"
        order = f"\nORDER BY {', '.join(step.group_by)}" if step.group_by else ""
        return f"SELECT {cols} FROM {safe_name(step.source) or 'src'}{order};"
    return f"-- MANUAL REVIEW: step `{step.name}` (kind={step.kind}) not emitted as SQL"


def _agg(step: AggStep) -> str:
    view = safe_name(step.name)
    src = safe_name(step.source) or "src"
    measures = []
    for m in step.measures:
        tmpl = _AGG_SQL.get(m.func, f"{m.func}({{c}})")
        col = "*" if m.column == "*" else m.column
        measures.append(tmpl.format(c=col) + f" AS {m.alias}")
    select_cols = list(step.group_by) + measures
    gb = f"\nGROUP BY {', '.join(step.group_by)}" if step.group_by else ""
    return (
        f"CREATE OR REPLACE TEMP VIEW {view} AS\n"
        f"SELECT {', '.join(select_cols)}\nFROM {src}{gb};"
    )


def _data(step: DataStep) -> str:
    view = safe_name(step.name)
    src = safe_name(step.source) or "src"
    cols = ["*"]
    if step.keep:
        cols = step.keep
    select = ", ".join(cols)
    for a in step.assignments:
        if a.condition:
            select += f",\n  CASE WHEN {a.condition} THEN {a.expr} END AS {a.target}"
        else:
            select += f",\n  {a.expr} AS {a.target}"
    where = f"\nWHERE {step.where}" if step.where else ""
    return f"CREATE OR REPLACE TEMP VIEW {view} AS\nSELECT {select}\nFROM {src}{where};"
